Apple background and gradient project
imran5644/apple_backgrounds_and_gradients pull request #1
Opened 2020-09-25 22:04 UTC by marcelomaidden

## Apple background and gradient project
In this project we used:

- Flexbox and grid to create the layout
- Float to create the footer section
- background-image with linear-gradient on the menu
- Navigation bar with border-radius

2020-09-25 23:13 UTC, blackpintz requested changes
# Status: Changes Required

### Hello team,

**Good job on your project. However, there are some few changes needed:**

1). **Reduce the extra width after the navbar search input, so it matches the original.**

original  |  clone
--------- |  ---------
![gradient_original](https://user-images.githubusercontent.com/38922385/94322641-b5015a80-ff9b-11ea-8b78-ce623b44541d.png) |  ![gradient_clone](https://user-images.githubusercontent.com/38922385/94322657-c2b6e000-ff9b-11ea-8b07-50d3af5ca3f7.png)

2). **The main content's background image doesn't cover the full-screen size. There is some white space at the rightmost part of the image.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/background_size_requirement.png) from pathwright)**

![background_clone](https://user-images.githubusercontent.com/38922385/94322943-bbdc9d00-ff9c-11ea-885a-f9e7cbe43b40.png)
 
3). **Remove the horizontal scroll.**

![scroll](https://user-images.githubusercontent.com/38922385/94323043-fa725780-ff9c-11ea-9597-0554917d245c.png)

**Check for one more comment below.**

## Best of luck 😃!

**PS: You can send me a message on slack(Rose Wanjohi)**

2020-09-25 23:13 UTC, ghost commented on stylesheets/style.css
> +  /* border-radius: 10px; */
Remove the comment on line 83.

2020-09-26 01:22 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-26 01:27 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @imran5644 and @marcelomaidden
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.

- [ ] Fix HTML validation [HTML Validation Screenshort](https://user-images.githubusercontent.com/29689273/94326828-4387d300-ffc0-11ea-865c-55e523f49f0a.png). You can check HTML validations in [validator.w3.org](https://validator.w3.org/)


### Header Background image
- [ ] Header background image is not covering the full screen (Previous TSE explained it)

|[Source Page](https://web.archive.org/web/20140301004610/http://www.apple.com/)|[Clone Page](https://rawcdn.githack.com/imran5644/apple_backgrounds_and_gradients/c23bd270138415152478e46f5d12791e02b7f8d0/index.html)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/94326887-c577fc00-ffc0-11ea-90d5-e1b40da5f797.png)|![clone](https://user-images.githubusercontent.com/29689273/94326897-d6287200-ffc0-11ea-9d15-198cdf566fe0.png)|



##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-28 17:11 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Hello team! Good job with this project, look pretty good! 👍 
Good job applying the changes 💯 
However, still one more change to apply before being approved! 💪 

Please, make the changes and resubmit your project for a new code review, so you can move into the next project ⏩ 

Check my comments below 👇 and good luck 😃 

- Your live link is not updated, so on your web, I still can see the horizontal scrollbar and some problems with the sizing, I had to create my own live link to check your changes, please update it, it is important that your live link works properly, just think it is the first thing the recruiters look at.

2020-09-28 17:44 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave: Hello Team!! Great work!

:100: nice implementing media queries even if the project didn't require it! :clap: :clap:

Great effort working on the previously requested changes. There are still, some issues to be addressed.

## Required Changes
### [Mandatory] :red_circle: 

- [ ] Feature branch should not be defaul branch.
![image](https://user-images.githubusercontent.com/25774518/94465626-ce65fa80-0185-11eb-83b3-4d6fe1af429d.png)

- [ ] Footer not aligned properly
![image](https://user-images.githubusercontent.com/25774518/94466044-6bc12e80-0186-11eb-8722-59b05e7e00b8.png)

- [ ] Remove duplicated Font-Awesome link from the head. See inline comments

- [ ] Remove unnecessary font Roboto link from the head. See inline comments

- [ ] Remove ```<div>``` container wrappers from block elements. See inline comments.

### [OPTIONAL]  :large_blue_circle: 

- [ ] Use 2 space indentation in HTML file. This helps improve Readability.

- [ ] ```<header>```, ```<main>```, and ```<footer>``` should be the most outer tags inside the ```<body>```. The background image for the hero section could be approached in another way.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-09-28 17:51 UTC, jubaan requested changes

2020-09-28 17:51 UTC, jubaan commented on index.html
> +                    </div>
- [ ] ```<h>```, and ```<p>``` are HTML block elements (not inline), using a div to wrap them is redundant and unnecessary.

2020-09-28 17:51 UTC, jubaan commented on index.html
> +            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
- [ ] Font awesome link is repeated.

- [ ] Roboto font link is repeated.

2020-09-28 18:24 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

Hello :+1: 

You did quite a good job here. However, you have some small problems in order to approve this project:

- [ ] You have linter errors. Kindly fix them
![image](https://user-images.githubusercontent.com/61479648/94470729-738ccd00-019e-11eb-9d16-ae79e6f21b5a.png)


- [ ] You have this that was requested in the previous review and still persists:

![image](https://user-images.githubusercontent.com/61479648/94470439-12fd9000-019e-11eb-9df3-19ae319f77de.png)

- [ ] You have a small problem in your footer:


| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/94470505-27418d00-019e-11eb-8a99-f0a7d6739fde.png) |![image](https://user-images.githubusercontent.com/61479648/94470780-830c1600-019e-11eb-8023-4d462a631069.png)  |

#### We are almost there. Kindly address those small issues so your project looks even better!

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-09-28 18:24 UTC, expjazz commented on index.html
> +            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
- [ ] Remove the extra font-awesome link

2020-09-28 18:57 UTC, jubaan approved these changes
# Status: Approved :tada: :tada: :tada:

## Congratulations Team :clap: :clap: :clap:!!

You may now merge to master.

### [OPTIONAL]

- [ ] Format the HTML file and remove the extra white space. See inline comment.

## See you at the top :rocket: !!

2020-09-28 18:58 UTC, jubaan commented on index.html
> +                </section>
- [ ] Remove extra white space

2020-09-28 19:01 UTC, merged